version: '3.8'
services:
  kibana:
    image: jamesgarside/kibana:7.11.1
    environment:
      SERVERNAME: localhost
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic
    ports: 
      - "5601:5601"
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    environment:
      - node.name=es01
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - elastic
volumes:
  data01:
networks:
  elastic:
    driver: overlay